### ISSUE TITLE
Cannot get dependecies

### ISSUE THREAD

**Issue by alexnix** [sqrlserverjava/sqrl-server-example#2]
I am getting the following error when mvn jetty:run

[ERROR] Failed to execute goal on project sqrlexample: Could not resolve dependencies for project com.github.sqrlserverjava:sqrlexample:war:0.7.2-SNAPSHOT: The following artifacts could not be resolved: com.github.sqrlserverjava:sqrl-server-base:jar:0.9.5-SNAPSHOT, com.github.sqrlserverjava:sqrl-server-atmosphere:jar:1.1.0-SNAPSHOT: Could not find artifact com.github.sqrlserverjava:sqrl-server-base:jar:0.9.5-SNAPSHOT -> [Help 1]

I am missing a command I should have typed before the mvn jettty:run or should I somehow add a repository for the two missing dependencies?

**Comment by alexnix** [comment]
Fixed: added JitPack

<repositories>
		<repository>
	    <id>jitpack.io</id>
	    <url>https://jitpack.io</url>
		</repository>
	</repositories>

**Comment by dbadia** [comment]
@alexnix Thanks for posting a solution.  The original error was due to me not uploading the latest SNAPSHOT versions to maven.  I will work on updating that.  Jitpack solution looks interesting
